### ISSUE TITLE
Can actually compile as .z5 if you want

### ISSUE THREAD

**Issue by jpcompton** [daelsepara/dead-men#1]
Not to be a pain about it, but you can actually compile to .z5 if you want. :) You just have to ignore zapf's rather stern warnings during zapf -ab and forge ahead with the freq.xzap it generates...

[deadmen.z5.zip](https://github.com/daelsepara/dead-men/files/4944119/deadmen.z5.zip)

**Comment by daelsepara** [comment]
Yes it does indeed. Thanks for that. I reverted back to z5 and modified the Makefile to ignore the zapf warnings when building the abbreviations. Meanwhile, I created a mini library that only included stuff from the zillib that were used by the game book framework e.g. READLINE, YES?, etc.
